assignments:
  host: github-dev.cs.illinois.edu
  org: cs225-staff
  repo: assignments
submissions:
  host: github-dev.cs.illinois.edu
  org: cs225sp18
grades:
  host: github-dev.cs.illinois.edu
  org: cs225-staff
  repo: sp18-autograder-grades
feedback:
  host: github-dev.cs.illinois.edu
  org: cs225-staff
  repo: sp18-studentFeedback
roster:
  - abhaymv2
  - abs4
  - achakr9
  - acl3
  - adamo2
  - adithya2
  - adityab3
  - aeh3
  - aelse2
  - aherath2
  - aierzha2
  - ajays2
  - ajm5
  - ajschro2
  - akerwin2
  - akhil2
  - akumar53
  - alanlh2
  - alanlu2
  - alanmm2
  - alexli2
  - althaus1
  - amalik26
  - amf2
  - amhou2
  - amukher6
  - amukund2
  - amzhou2
  - ananda6
  - anb4
  - andrewg3
  - ankitd2
  - ankitr2
  - ankurm2
  - ankusha2
  - anmoln2
  - apanwa3
  - aqures22
  - arkisho2
  - arnav2
  - arnavmd2
  - arodri23
  - arshb2
  - as6
  - asa2
  - asadnej2
  - asensio3
  - asevers2
  - ashi6
  - asrnvsn4
  - aukey2
  - austinb3
  - axu5
  - ayushs2
  - az3
  - azriela2
  - bagga2
  - balline2
  - bc7
  - bcannel2
  - becarro2
  - belagam2
  - bfwang2
  - binfeng2
  - binghui2
  - bingxue3
  - binpeng2
  - bjwong2
  - bkoott2
  - bldu2
  - bmw4
  - bohanz2
  - bost2
  - bowang12
  - bpankow2
  - bpl2
  - bpv2
  - btf2
  - bts2
  - bwort2
  - byen2
  - bzinn2
  - canlinz2
  - cao37
  - cao38
  - caryzc2
  - caubry2
  - cb4
  - cchen160
  - cclally2
  - ccoron7
  - cd2
  - cf7
  - cgan4
  - ch4
  - chaeyun2
  - chairez2
  - chasea2
  - chenghu3
  - chenhao3
  - chenkai3
  - chomiak2
  - cjdicks2
  - cjzhu2
  - cli94
  - clj2
  - cstsai2
  - cszul2
  - cw3
  - cwchang2
  - cxia5
  - czzhang2
  - dadomin2
  - dan5
  - danielm2
  - danjinj2
  - davidjd2
  - davidjl2
  - davidmc2
  - davinw2
  - dbiskup2
  - dcyee2
  - ddore3
  - dec2
  - desetty2
  - dflanag2
  - dgshah2
  - didrick2
  - dillonh2
  - dirosen2
  - diyuy2
  - djh4
  - dk2
  - dkim287
  - dkozak3
  - dlin16
  - dmathur2
  - dmr2
  - dniess2
  - dobon2
  - dohunj2
  - dongxin2
  - dpate212
  - dpratap2
  - draskin2
  - dscheng3
  - dschoi3
  - dterpay2
  - dugad2
  - duoruix2
  - dwlim2
  - dy2
  - dykang2
  - ead2
  - ebracht2
  - edwardp3
  - egarci90
  - ejcao2
  - ekim115
  - elgendy2
  - elliots2
  - emmat2
  - emoog2
  - emroch2
  - emysliw2
  - epan2
  - epang3
  - erikj2
  - esc2
  - eshen5
  - espino2
  - evanic2
  - eyc3
  - fangwei2
  - fc2
  - feiyang3
  - fejer2
  - fenghou2
  - fengmao2
  - fengzej2
  - fengzex2
  - fhan4
  - fherna30
  - fling2
  - fmui2
  - foyuma2
  - francst2
  - fulkrod2
  - fyang19
  - gaguir7
  - gaj3
  - gajansk2
  - garyab2
  - gassel2
  - gcolvin2
  - geonilk2
  - gl5
  - gotsis2
  - gouyang2
  - grossfe2
  - gs10
  - gtandon2
  - hadyer2
  - hahm4
  - haigec2
  - haiming2
  - haitaol2
  - hankily2
  - hansun3
  - hanzes2
  - haofeng5
  - haol4
  - haoranl3
  - haorong4
  - haoyuw2
  - haoyuz3
  - harshh2
  - hc10
  - hding10
  - helenac2
  - henryh2
  - henryw2
  - hf2
  - hfu6
  - hhuang81
  - hiraald2
  - hkansa2
  - hli106
  - hma14
  - hongyuw2
  - howards2
  - hpate63
  - hqiu9
  - hrnndzc2
  - hsolom2
  - hsong38
  - hx2
  - hxu58
  - hyun14
  - hzdeng2
  - hzhng120
  - iraiter2
  - irdutta2
  - irodri30
  - ishanp2
  - iwanaga2
  - janette2
  - jas3
  - javedm2
  - jbyster2
  - jcepeda2
  - jchen249
  - jdadamo2
  - jdiamnd2
  - jdirr2
  - jdshah3
  - jea2
  - jeelbt2
  - jeenalt2
  - jehwang2
  - jflore74
  - jfzhang2
  - jhan80
  - jiaqing2
  - jiaruiz3
  - jiayil5
  - jihyunl2
  - jingjin9
  - jingyiw3
  - jinsooo2
  - jjleuck2
  - jjlu2
  - jkim460
  - jkim554
  - jkim557
  - jky2
  - jlee760
  - jliu128
  - jmier2
  - jmufuta2
  - joan2
  - johnkan2
  - josborn3
  - josephy2
  - joshuas6
  - jpark318
  - jplau2
  - jsanch84
  - jsingh42
  - jtang47
  - jtmulle2
  - juefeic2
  - jueh2
  - jurkwcz2
  - justinf2
  - justinr3
  - jw7
  - jyhu2
  - jz32
  - jzhou60
  - jzw2
  - kab2
  - kabrol2
  - kaempen2
  - kandmll2
  - keertic2
  - kehan2
  - kehangc2
  - keri2
  - keshavh2
  - kesun5
  - kg9
  - kgoenka2
  - kkalki2
  - kkamal2
  - kkansal2
  - klguill2
  - koiloth2
  - koweic2
  - kpf2
  - kristbp2
  - kroczyn2
  - krthmps2
  - ksethi4
  - kshivam2
  - ksrnvsn2
  - ksurti2
  - kthakkr2
  - kwang49
  - kwoo3
  - kyang15
  - kylegb2
  - kys2
  - kyu17
  - kzhagui2
  - lahess
  - lamvo2
  - lanwang2
  - leyaoz2
  - liamjw2
  - linus2
  - lisaly2
  - liwenwu2
  - liwenz2
  - lma16
  - loganap2
  - loleng2
  - lujiak2
  - lukeang2
  - luo35
  - lyang57
  - mal7
  - manahil2
  - mapope2
  - mbackas2
  - mbaig44
  - mbiju2
  - mcardi3
  - mchen78
  - mcjohns5
  - mdb2
  - mdd2
  - medhar2
  - meganew2
  - mfelix2
  - mgarc67
  - mgb3
  - mgrover3
  - miaoh2
  - migdal2
  - mihikaa2
  - milanmd2
  - minerl2
  - minhql2
  - mirecki2
  - mishap2
  - mitalee2
  - mjcoone2
  - mjluo2
  - mjshea3
  - mkim146
  - mkw2
  - mmccrac2
  - mmweiga2
  - mohdfau2
  - mpatan2
  - mqian9
  - mrizvi5
  - mrn2
  - mross22
  - mruijie2
  - msa5
  - msahmed3
  - msvogt2
  - mtuan2
  - mwillms7
  - mwrisin2
  - my4
  - myun7
  - mzou6
  - nbf2
  - nc7
  - nhelms2
  - nikhilm2
  - nikhilm3
  - nju2
  - nliu11
  - nmanda2
  - nmikha2
  - nmistr4
  - np9
  - nparmar2
  - nperujo2
  - ns10
  - nsomers2
  - nwutt2
  - oesmail2
  - old2
  - oscaro2
  - otaha2
  - parthgp2
  - parthp2
  - paulrr2
  - pavanh2
  - pengjin2
  - peterhl2
  - pfeltes2
  - pgc2
  - pjg4
  - pli29
  - plovete2
  - ppiatek2
  - pppatel9
  - pradaxa2
  - pragyaa2
  - prc2
  - prm2
  - prpatel7
  - pruthvi2
  - psanan3
  - pshome2
  - puebla2
  - pwk2
  - pyyang2
  - qdong4
  - qhuang25
  - qilanz2
  - qingyuw2
  - qm2
  - qputnam2
  - qqian7
  - quanjie2
  - ragolli2
  - rajeevp2
  - ranwang2
  - rbasara2
  - rcshank2
  - rdeshmu2
  - reedoei2
  - reishac2
  - reo2
  - rishabh3
  - rishipd2
  - rittika2
  - rizhaoq2
  - rjlong2
  - rljames2
  - rmasand2
  - roglans3
  - rohinb2
  - rohink2
  - rongw2
  - roxas2
  - rsj2
  - rtmikes2
  - rturza2
  - ruchia2
  - ruip2
  - ruixinz2
  - rvarga2
  - sahils2
  - samarth2
  - sameerv2
  - sarahmh2
  - sasingh3
  - sbachu2
  - sbalaji3
  - sbarre24
  - sc31
  - schen171
  - scottk3
  - sdesai49
  - sding9
  - sebe2
  - sejalkp2
  - selenaj2
  - serfan2
  - sg2
  - shaynak2
  - shiroka2
  - shixinw2
  - shreyak4
  - shreyc2
  - shriya2
  - shuangs3
  - shuyanl3
  - shuyuez2
  - shzhang2
  - sicong3
  - sid2
  - sieger2
  - simley2
  - siyecen2
  - siyuniu2
  - siyutao2
  - sizhetu2
  - sjang27
  - sjdesai3
  - sjiao2
  - sjpatel7
  - sjw2
  - skim586
  - sl38
  - slam20
  - slee454
  - sluo24
  - sm13
  - smishr25
  - smodi9
  - smrizvi2
  - snori2
  - sohams2
  - songtao2
  - sophias2
  - soterob2
  - srirams2
  - ss27
  - ss4
  - sshah247
  - sshaik9
  - ssriram3
  - sssrira2
  - ssv2
  - surjosd2
  - sutthas2
  - suvena2
  - svnktsh3
  - sxchew2
  - sxiong13
  - syrek2
  - sz9
  - szheng25
  - szhou53
  - tandale2
  - taosun2
  - tbu2
  - tejaswi2
  - tfd2
  - thomash3
  - tianpei2
  - tianren2
  - tiansun2
  - tianyul2
  - tinfang2
  - tja2
  - tk2
  - tln2
  - tmccrth2
  - tml2
  - tonykim2
  - tpu3
  - trpgbll2
  - ts8
  - ttatro2
  - twjudd2
  - tylerjd2
  - tzhang74
  - ub3
  - usrida2
  - vaidehi3
  - varadk2
  - varung2
  - vbajaj4
  - vbojja2
  - vijaygk2
  - vishwan3
  - vk2
  - vkp2
  - vmurthy2
  - vnt2
  - vpatel35
  - vpuri3
  - vramana2
  - vygoel2
  - wasicki2
  - wasowic2
  - wcwang2
  - wenjiey2
  - wenjuns2
  - wenqian3
  - wens2
  - wenshan2
  - wlee94
  - wolan2
  - wwang114
  - wyhwang2
  - xc14
  - xcao14
  - xchen146
  - xhe16
  - xiaoyis2
  - xiaying2
  - xingzhi2
  - xinhang2
  - xintong2
  - xinyig2
  - xiuyiqin
  - xiziy2
  - xl16
  - yankunz2
  - yanxu3
  - yanyeli2
  - yaox4
  - yarora3
  - yashuow2
  - ychu26
  - yf3
  - yichi3
  - yifan8
  - yifeixu2
  - yiliut2
  - yinfeiz2
  - yinz3
  - yipengh3
  - yixino3
  - yiyaoz4
  - yjhuang2
  - ykwok4
  - yming3
  - ysong93
  - ytark2
  - yuchecw2
  - yuchenw2
  - yuefeng3
  - yuejun2
  - yuexu8
  - yuhengc2
  - yujiay2
  - yuming2
  - yumingj2
  - yuwang15
  - yuxuang3
  - yuzhao4
  - yxu68
  - yyoshid3
  - yzhong22
  - zekunhu2
  - zepengx2
  - zh9
  - zhilil2
  - zhining4
  - zhixinw2
  - zhou110
  - zhuyunz2
  - zihongz2
  - zijins2
  - zipengy2
  - ziqiaom2
  - zixinl2
  - zixiong2
  - ziyic2
  - zizhang2
  - zji5
  - zjiang30
  - zs2
  - zuodong2
  - zz7
