assignments:
  host: github-dev.cs.illinois.edu
  owner: cs225-staff
  repo: assignments
submissions:
  host: github-dev.cs.illinois.edu
  owner: cs225sp18
grades:
  host: github-dev.cs.illinois.edu
  owner: cs225-staff
  repo: sp18-autograder-grades
feedback:
  host: github-dev.cs.illinois.edu
  owner: cs225-staff
  repo: sp18-studentFeedback
roster:
  - nwalter2
  - waf
